export const EVENT_RESIZE_PANEL = "EVENT_RESIZE_PANEL";
export const EVENT_DATA_UPDATE = "EVENT_DATA_UPDATE";
export const EVENT_CAMERA_UPDATE = "EVENT_CAMERA_UPDATE";
export const EVENT_RENDERING_UPDATE = "EVENT_RENDERING_UPDATE";
export const EVENT_RENDERING_UPDATE_CLICKED_POSITION = "EVENT_RENDERING_UPDATE_CLICKED_POSITION";

export const BEHAVIOR_CONTROL_CAMERA = "BEHAVIOR_CONTROL_CAMERA";
export const BEHAVIOR_MOVE_SEED = "BEHAVIOR_MOVE_SEED";

export const TEXTURE_MODE_SPECIALIZED = 0;
export const TEXTURE_MODE_RAW_VIRTUAL = 1;
export const TEXTURE_MODE_RAW_TEXTURE = 2;

export const TEXTURE_MODE_SPECIALIZED_GRAVITATIONAL_FORCE = 0;
export const TEXTURE_MODE_SPECIALIZED_GRAVITATIONAL_FORCE_MAGNITUDE = 1;

export const OFFSCREEN_RENDERER_SEEDS = 0;
export const OFFSCREEN_RENDERER_GRAVITATIONAL_FORCE = 1;
export const OFFSCREEN_RENDERER_FLOW_MAP = 2;

export const TERMINATION_METHOD_UNLIMITED = "0";
export const TERMINATION_METHOD_FIRST_RETURN = "1";
export const TERMINATION_METHOD_SECOND_RETURN = "2";