export const EVENT_RESIZE_PANEL = "EVENT_RESIZE_PANEL";
export const EVENT_DATA_UPDATE_PHYSICS = "EVENT_DATA_UPDATE_PHYSICS"
export const EVENT_CALCULATE_FTLE = "EVENT_CALCULATE_FTLE";
export const EVENT_CAMERA_UPDATE_CONTROLS = "EVENT_CAMERA_UPDATE_CONTROLS";
export const EVENT_RENDERING_UPDATE_BODIES = "EVENT_RENDERING_UPDATE_BODIES";
export const EVENT_RENDERING_UPDATE_CLICKED_POSITION = "EVENT_RENDERING_UPDATE_CLICKED_POSITION";

