export const EVENT_RESIZE_PANEL = "EVENT_RESIZE_PANEL";
export const EVENT_DATA_UPDATE = "EVENT_DATA_UPDATE";
export const EVENT_CAMERA_UPDATE = "EVENT_CAMERA_UPDATE";
export const EVENT_RENDERING_UPDATE = "EVENT_RENDERING_UPDATE";
export const EVENT_RENDERING_UPDATE_CLICKED_POSITION = "EVENT_RENDERING_UPDATE_CLICKED_POSITION";

export const BEHAVIOR_CONTROL_CAMERA = "BEHAVIOR_CONTROL_CAMERA";
export const BEHAVIOR_MOVE_SEED = "BEHAVIOR_MOVE_SEED";

export const TEXTURE_MODE_SPECIALIZED = "0";
export const TEXTURE_MODE_RAW_VIRTUAL = "1";
export const TEXTURE_MODE_RAW_TEXTURE = "2";